@url_localhost = http://[::1]:3000/dev
@url = https://oo3cf0l0p7.execute-api.us-east-1.amazonaws.com/dev/todo
###
GET {{url}}

###
DELETE {{url}}/54081102-f6d7-4cba-997b-73eac03602ef

###
POST {{url}}
Content-Type: application/json

{
    "title": "task-1",
    "description": "details"
}

###
PATCH {{url}}/54081102-f6d7-4cba-997b-73eac03602ef
Content-Type: application/json

{
    "title": "task-2",
    "status": true
}

