@url_localhost = http://[::1]:3000/dev/todo
@url = https://vrtort8x3f.execute-api.us-east-1.amazonaws.com/dev/todo
###
GET {{url}}

###
DELETE {{url}}/05d2e743-be8b-4748-b672-2f0189b6863a

###
POST {{url}}
Content-Type: application/json

{
    "title": "task-1",
    "description": "hello world"
}

###
PATCH {{url}}/1b6b0463-669d-415e-8beb-78b67c5403f8
Content-Type: application/json

{
    "title":"task-1",
    "status": true
}

